User can edit an entry - Cathy Garcia
cathyygrcia/code-journal pull request #9
Opened 2023-08-08 02:06 UTC by cathyygrcia

https://github.com/cathyygrcia/code-journal/assets/90016242/1ebafa7b-c63b-4923-9d63-61a67a98d905

2023-08-08 04:16 UTC, shawnkost requested changes
Just need to fix the CSS change I messaged you about. The "Code Journal" text & the "Entries" text below it should be aligned. Left one other suggestion though

2023-08-08 04:16 UTC, shawnkost commented on js/main.js
> +    viewSwap('entry-form');
I would call this after the loop, that way we swap after the inputs were filled in

2023-08-09 00:29 UTC, cathyygrcia commented
https://github.com/cathyygrcia/code-journal/assets/90016242/7cf3b8df-724c-4a9e-be9e-10d4046177d7

2023-08-09 01:48 UTC, shawnkost approved these changes
👍

2023-08-09 02:09 UTC, merged